apiVersion: v1
kind: Pod
metadata:
  name: kcontrol
  namespace: kafka
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-enterprise-control-center:4.1.0
    env:
    - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
      value: "my-kafka-zookeeper.kafka:2181"
    - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
      value: "my-kafka-kafka.kafka:9092"
    - name: CONTROL_CENTER_REPLICATION_FACTOR
      value: "1"
    - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
      value: "1"
    - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
      value: "1"
    - name: CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS
      value: "2"
    - name: CONTROL_CENTER_CONNECT_CLUSTER
      value: "connect.kafka:28082"

