apiVersion: v1
kind: Pod
metadata:
  name: kconnect
  namespace: kafka
  labels:
      service: connect
spec:
  containers:
  - name: connect
    image:  nginmesh/kafka-connect:4.1.0
    env:
    - name: CONNECT_BOOTSTRAP_SERVERS
      value: "my-kafka-kafka.kafka:9092"
    - name: CONNECT_REST_PORT
      value: "28082"
    - name: CONNECT_GROUP_ID
      value: "quickstart"
    - name: CONNECT_CONFIG_STORAGE_TOPIC
      value: "quickstart-config"
    - name: CONNECT_OFFSET_STORAGE_TOPIC
      value: "quickstart-offsets"
    - name: CONNECT_STATUS_STORAGE_TOPIC
      value: "quickstart-status"
    - name: CONNECT_PRODUCER_INTERCEPTOR_CLASSES
      value: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
    - name: CONNECT_CONSUMER_INTERCEPTOR_CLASSES
      value: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
    - name: CONNECT_KEY_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: CONNECT_VALUE_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: CONNECT_INTERNAL_KEY_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: CONNECT_INTERNAL_VALUE_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: CONNECT_REST_ADVERTISED_HOST_NAME
      value: "localhost"
    - name: CONNECT_LOG4J_ROOT_LOGLEVEL
      value: "INFO"
    - name: CONNECT_LOG4J_LOGGERS
      value: "org.reflections=ERROR"
    - name: CONNECT_PLUGIN_PATH
      value: "/usr/share/java"
    - name: CONNECT_REST_HOST_NAME
      value: "localhost"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: connect
  name: connect
  namespace: kafka
spec:
  ports:
  - protocol: "TCP"
    port: 28082
    targetPort: 28082
  selector:
    service: connect