# https://github.com/confluentinc/ksql/blob/4.1.0-post/docs/tutorials/docker-compose.ymlapiVersion: v1
apiVersion: v1
kind: Pod
metadata:
  name: ksql-cli
  namespace: kafka
spec:
  containers:
  - name: ksql
    image:  confluentinc/ksql-cli:4.1.0
    env:
    - name: KSQL_CONFIG_DIR
      value: "/etc/ksql"
    - name: KSQL_LOG4J_OPTS
      value: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
    - name: KSQL_OPTS
      value: "-Dbootstrap.servers=my-kafka-kafka.kafka:9092 -Dlisteners=http://0.0.0.0:8088"
    command:
      - /usr/bin/ksql-server-start
      - "/etc/ksql/ksql-server.properties"
